import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Footer from "@/components/base/footer";
import Header from "@/components/base/header";
import Provider from "@/providers";
import { cn } from "@/lib/utils";
import Container from "@/components/layout/container";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "antialiased min-h-screen")}>
        <Provider>
          <div className="h-screen flex flex-col">
            <Header />
            <div className="flex-1 relative">
              <div className="absolute inset-0 overflow-y-auto">
                <Container className="h-full">{children}</Container>
              </div>
            </div>
            <Footer />
          </div>
        </Provider>
      </body>
    </html>
  );
}
